# Sesión 6

En esta sesión se usará la base de datos relacional `classicmodels` (MySQL), compuesta por las siguientes tablas:

*   `Customers`: almacena los datos de los clientes.
*   `Products`: almacena una lista de modelos de coches a escala.
*   `ProductLines`: almacena una lista de categorías de líneas de productos.
*   `Orders`: almacena los pedidos de venta realizados por los clientes.
*   `OrderDetails`: almacena elementos de línea de pedidos de ventas para cada pedido de ventas.
*   `Payments`: almacena los pagos realizados por los clientes en función de sus cuentas.
*   `Employees`: almacena toda la información de los empleados, así como la estructura de la organización, como quién informa a quién.
*   `Offices`: almacena los datos de la oficina de ventas.

Recordatorio:

+ Una **clave/llave primaria** es un atributo (o conjunto) que identifica unívocamente a cada registro en la tabla.
+ Una **clave/llave foránea** (externa o ajena) es un atributos (o conjunto) en una tabla que es una clave primaria en otra (o posiblemente la misma) tabla.
+ Lo comento porque haremos unos joins en esta sesión

# SQLAlchemy y SQL básico

+ Para hacer la conexión entre SQL y Python usaré la libreóa SQLAlchemy

In [1]:
!pip install pymysql
# Se ejecuta una vez para la instalación del módulo/librería

Requirement already satisfied: pymysql in /usr/local/lib/python3.12/dist-packages (1.1.2)

In [2]:
import sqlalchemy as sqla
import pymysql
import pandas as pd

from sqlalchemy import inspect
from sqlalchemy import text

Se creará el motor `sqlalchemy`, con el método `create_engine()` y una conexión con `connect()`

+ Como antes, en realidad Python sólo hare solicitudes y recibirá respuestas de un sistama de bases de datos (mySQL) hecho y derecho.

+ ¿A que sistema nos conectaremos?

+ La Czech Technical University (CTU) en Praga  tiene un repositorio público con esta base de datos para practicar: `classicmodels`.

+ **OJO:** Si estamas inactivos por un rato cierra la conexión y la tenemos que volver a hacer.

+ Host: relational.fel.cvut.cz
+ Usuario: guest
+ Password: ctu-relational
+ Puerto: 3306

+ Esto en realidad es sólo informativo, la conexión la hacemos con el siguiente string

In [3]:
# Se crea el motor (dialecto://usuarioBD:clave@ipHostDBMS:puerto/esquema
db = sqla.create_engine('mysql+pymysql://guest:ctu-relational@relational.fel.cvut.cz:3306/classicmodels')

In [4]:
# Crea una conexión para luego invocar declaraciones SQL con la función connect()
conn = db.connect()

In [5]:
# Qué tipo de objeto es conn
conn

In [6]:
# Primero veremos el nombre de las tablas contenidas en la base
# de datos para eso ocupamos la función inspect
inspector = inspect(db)

# Se obtendrá el nombre de las tablas en dicha base de datos
inspector.get_table_names()

['customers',
 'employees',
 'offices',
 'orderdetails',
 'orders',
 'payments',
 'productlines',
 'products']

In [7]:
# Se puede obtener los nombres de la columna de cada una de
# de las tablas de la base de datos
# Por ejemplo, para la tabla 'customers'
inspector.get_columns('customers')

[{'name': 'customerNumber',
  'type': INTEGER(display_width=11),
  'default': None,
  'comment': None,
  'nullable': False,
  'autoincrement': False},
 {'name': 'customerName',
  'type': VARCHAR(length=50),
  'default': None,
  'comment': None,
  'nullable': False},
 {'name': 'contactLastName',
  'type': VARCHAR(length=50),
  'default': None,
  'comment': None,
  'nullable': False},
 {'name': 'contactFirstName',
  'type': VARCHAR(length=50),
  'default': None,
  'comment': None,
  'nullable': False},
 {'name': 'phone',
  'type': VARCHAR(length=50),
  'default': None,
  'comment': None,
  'nullable': False},
 {'name': 'addressLine1',
  'type': VARCHAR(length=50),
  'default': None,
  'comment': None,
  'nullable': False},
 {'name': 'addressLine2',
  'type': VARCHAR(length=50),
  'default': None,
  'comment': None,
  'nullable': True},
 {'name': 'city',
  'type': VARCHAR(length=50),
  'default': None,
  'comment': None,
  'nullable': False},
 {'name': 'state',
  'type': VARCHAR(length=50),
  'default': None,
  'comment': None,
  'nullable': True},
 {'name': 'postalCode',
  'type': VARCHAR(length=15),
  'default': None,
  'comment': None,
  'nullable': True},
 {'name': 'country',
  'type': VARCHAR(length=50),
  'default': None,
  'comment': None,
  'nullable': False},
 {'name': 'salesRepEmployeeNumber',
  'type': INTEGER(display_width=11),
  'default': None,
  'comment': None,
  'nullable': True,
  'autoincrement': False},
 {'name': 'creditLimit',
  'type': DOUBLE(asdecimal=True),
  'default': None,
  'comment': None,
  'nullable': True}]

+ Como esta forma de leer las columnas de la tabla, la convertiré en pandas DataFrame

In [8]:
# Se convierte a un dataframe para mejor lectura
pd.DataFrame.from_dict(inspector.get_columns('customers'))

,name,type,default,comment,nullable,autoincrement
0,customerNumber,INTEGER,None,None,False,False
1,customerName,VARCHAR(50),None,None,False,NaN
2,contactLastName,VARCHAR(50),None,None,False,NaN
3,contactFirstName,VARCHAR(50),None,None,False,NaN
4,phone,VARCHAR(50),None,None,False,NaN
5,addressLine1,VARCHAR(50),None,None,False,NaN
6,addressLine2,VARCHAR(50),None,None,True,NaN
7,city,VARCHAR(50),None,None,False,NaN
8,state,VARCHAR(50),None,None,True,NaN
9,postalCode,VARCHAR(15),None,None,True,NaN
10,country,VARCHAR(50),None,None,False,NaN
11,salesRepEmployeeNumber,INTEGER,None,None,True,False
12,creditLimit,DOUBLE,None,None,True,NaN

Y así podemos ver más fácilmente las columnas de cada tabla

In [9]:
pd.DataFrame.from_dict(inspector.get_columns('offices'))

           name         type default comment  nullable
0    officeCode  VARCHAR(10)    None    None     False
1          city  VARCHAR(50)    None    None     False
2         phone  VARCHAR(50)    None    None     False
3  addressLine1  VARCHAR(50)    None    None     False
4  addressLine2  VARCHAR(50)    None    None      True
5         state  VARCHAR(50)    None    None      True
6       country  VARCHAR(50)    None    None     False
7    postalCode  VARCHAR(15)    None    None     False
8     territory  VARCHAR(10)    None    None     False

## Algunas queries sencillas

In [10]:
# Veamos las columnas de la tabla 'productlines'
pd.DataFrame.from_dict(inspector.get_columns('productlines'))

              name           type default comment  nullable
0      productLine    VARCHAR(50)    None    None     False
1  textDescription  VARCHAR(4000)    None    None      True
2  htmlDescription     MEDIUMTEXT    None    None      True
3            image     MEDIUMBLOB    None    None      True

In [11]:
# Query para obtener la información de las líneas de productos.
mi_query = text('SELECT * FROM productlines')

In [12]:
# Qué tipo de objeto es
mi_query

In [13]:
# Hacemos un query
query = conn.execute(mi_query)

# Se imprime el resultado:
for row in query:
    print(row)

('Classic Cars', 'Attention car enthusiasts: Make your wildest car ownership dreams come true. Whether you are looking for classic muscle cars, dream sports cars or mo ... (437 characters truncated) ... cles. All models include a certificate of authenticity from their manufacturers and come fully assembled and ready for display in the home or office.', None, None)
('Motorcycles', 'Our motorcycles are state of the art replicas of classic as well as contemporary motorcycle legends such as Harley Davidson, Ducati and Vespa. Models ... (297 characters truncated) ...  out-of-production vehicles. All models come fully assembled and ready for display in the home or office. Most include a certificate of authenticity.', None, None)
('Planes', 'Unique, diecast airplane and helicopter replicas suitable for collections, as well as home, office or classroom decorations. Models contain stunning  ... (55 characters truncated) ... jet engines and propellers, retractable wheels, and so on. Most come fully assembled and with a certificate of authenticity from their manufacturers.', None, None)
('Ships', 'The perfect holiday or anniversary gift for executives, clients, friends, and family. These handcrafted model ships are unique, stunning works of art ... (12 characters truncated) ... e treasured for generations! They come fully assembled and ready for display in the home or office. We guarantee the highest quality, and best value.', None, None)
('Trains', "Model trains are a rewarding hobby for enthusiasts of all ages. Whether you're looking for collectible wooden trains, electric streetcars or locomoti ... (73 characters truncated) ... egory. The interactive aspect of trains makes toy trains perfect for young children. The wooden train sets are ideal for children under the age of 5.", None, None)
('Trucks and Buses', 'The Truck and Bus models are realistic replicas of buses and specialized trucks produced from the early 1920s to present. The models range in size fr ... (124 characters truncated) ... n, diecast and plastic. All models include a certificate of authenticity from their manufacturers and are a perfect ornament for the home and office.', None, None)
('Vintage Cars', 'Our Vintage Car models realistically portray automobiles produced from the early 1900s through the 1940s. Materials used include Bakelite, diecast, p ... (202 characters truncated) ... icas. All models include a certificate of authenticity from their manufacturers and come fully assembled and ready for display in the home or office.', None, None)

In [14]:
# Veamos las columnas de la tabla 'employees'
pd.DataFrame.from_dict(inspector.get_columns('employees'))

             name          type default comment  nullable autoincrement
0  employeeNumber       INTEGER    None    None     False         False
1        lastName   VARCHAR(50)    None    None     False           NaN
2       firstName   VARCHAR(50)    None    None     False           NaN
3       extension   VARCHAR(10)    None    None     False           NaN
4           email  VARCHAR(100)    None    None     False           NaN
5      officeCode   VARCHAR(10)    None    None     False           NaN
6       reportsTo       INTEGER    None    None      True         False
7        jobTitle   VARCHAR(50)    None    None     False           NaN

In [15]:
# Hacemos una query para obtener los empleados ordenados por nombre.
mi_query = text("""
    SELECT *
    FROM employees
    ORDER BY firstName ASC;
""")

query = conn.execute(mi_query)

# Se imprime el resultado:
for row in query:
    print(row)

(1611, 'Fixter', 'Andy', 'x101', 'afixter@classicmodelcars.com', '6', 1088, 'Sales Rep')
(1143, 'Bow', 'Anthony', 'x5428', 'abow@classicmodelcars.com', '1', 1056, 'Sales Manager (NA)')
(1504, 'Jones', 'Barry', 'x102', 'bjones@classicmodelcars.com', '7', 1102, 'Sales Rep')
(1002, 'Murphy', 'Diane', 'x5800', 'dmurphy@classicmodelcars.com', '1', None, 'President')
(1286, 'Tseng', 'Foon Yue', 'x2248', 'ftseng@classicmodelcars.com', '3', 1143, 'Sales Rep')
(1323, 'Vanauf', 'George', 'x4102', 'gvanauf@classicmodelcars.com', '3', 1143, 'Sales Rep')
(1102, 'Bondur', 'Gerard', 'x5408', 'gbondur@classicmodelcars.com', '4', 1056, 'Sale Manager (EMEA)')
(1370, 'Hernandez', 'Gerard', 'x2028', 'ghernande@classicmodelcars.com', '4', 1102, 'Sales Rep')
(1076, 'Firrelli', 'Jeff', 'x9273', 'jfirrelli@classicmodelcars.com', '1', 1002, 'VP Marketing')
(1188, 'Firrelli', 'Julie', 'x2173', 'jfirrelli@classicmodelcars.com', '2', 1143, 'Sales Rep')
(1501, 'Bott', 'Larry', 'x2311', 'lbott@classicmodelcars.com', '7', 1102, 'Sales Rep')
(1165, 'Jennings', 'Leslie', 'x3291', 'ljennings@classicmodelcars.com', '1', 1143, 'Sales Rep')
(1166, 'Thompson', 'Leslie', 'x4065', 'lthompson@classicmodelcars.com', '1', 1143, 'Sales Rep')
(1337, 'Bondur', 'Loui', 'x6493', 'lbondur@classicmodelcars.com', '4', 1102, 'Sales Rep')
(1621, 'Nishi', 'Mami', 'x101', 'mnishi@classicmodelcars.com', '5', 1056, 'Sales Rep')
(1702, 'Gerard', 'Martin', 'x2312', 'mgerard@classicmodelcars.com', '4', 1102, 'Sales Rep')
(1056, 'Patterson', 'Mary', 'x4611', 'mpatterso@classicmodelcars.com', '1', 1002, 'VP Sales')
(1401, 'Castillo', 'Pamela', 'x2759', 'pcastillo@classicmodelcars.com', '4', 1102, 'Sales Rep')
(1612, 'Marsh', 'Peter', 'x102', 'pmarsh@classicmodelcars.com', '6', 1088, 'Sales Rep')
(1216, 'Patterson', 'Steve', 'x4334', 'spatterson@classicmodelcars.com', '2', 1143, 'Sales Rep')
(1619, 'King', 'Tom', 'x103', 'tking@classicmodelcars.com', '6', 1088, 'Sales Rep')
(1088, 'Patterson', 'William', 'x4871', 'wpatterson@classicmodelcars.com', '6', 1056, 'Sales Manager (APAC)')
(1625, 'Kato', 'Yoshimi', 'x102', 'ykato@classicmodelcars.com', '5', 1621, 'Sales Rep')

Nótese que la lectura es poco legible para las personas

In [16]:
# Vemos las columnas de la tabla 'offices'
pd.DataFrame.from_dict(inspector.get_columns('offices'))

           name         type default comment  nullable
0    officeCode  VARCHAR(10)    None    None     False
1          city  VARCHAR(50)    None    None     False
2         phone  VARCHAR(50)    None    None     False
3  addressLine1  VARCHAR(50)    None    None     False
4  addressLine2  VARCHAR(50)    None    None      True
5         state  VARCHAR(50)    None    None      True
6       country  VARCHAR(50)    None    None     False
7    postalCode  VARCHAR(15)    None    None     False
8     territory  VARCHAR(10)    None    None     False

In [17]:
# Hacemos un query para obtener los países donde hay oficinas
mi_query = text("""
    SELECT DISTINCT country
    FROM offices;
""")

query = conn.execute(mi_query)

# Se imprime el resultado:
for row in query:
    print(row)

('USA',)
('France',)
('Japan',)
('Australia',)
('UK',)

In [18]:
# Vemos las columnas de la tabla 'customers'
pd.DataFrame.from_dict(inspector.get_columns('customers'))

,name,type,default,comment,nullable,autoincrement
0,customerNumber,INTEGER,None,None,False,False
1,customerName,VARCHAR(50),None,None,False,NaN
2,contactLastName,VARCHAR(50),None,None,False,NaN
3,contactFirstName,VARCHAR(50),None,None,False,NaN
4,phone,VARCHAR(50),None,None,False,NaN
5,addressLine1,VARCHAR(50),None,None,False,NaN
6,addressLine2,VARCHAR(50),None,None,True,NaN
7,city,VARCHAR(50),None,None,False,NaN
8,state,VARCHAR(50),None,None,True,NaN
9,postalCode,VARCHAR(15),None,None,True,NaN
10,country,VARCHAR(50),None,None,False,NaN
11,salesRepEmployeeNumber,INTEGER,None,None,True,False
12,creditLimit,DOUBLE,None,None,True,NaN

In [19]:
# Hacemos un query para obtener el nombre y teléfono de los clientes de Nueva York (*NYC*).

mi_query = text("""
    SELECT customerName, phone, city
    FROM customers
    WHERE city = "NYC";
""")

query = conn.execute(mi_query)

# Se imprime el resultado:
for row in query:
    print(row)

('Land of Toys Inc.', '2125557818', 'NYC')
('Muscle Machine Inc', '2125557413', 'NYC')
('Vitachrome Inc.', '2125551500', 'NYC')
('Classic Legends Inc.', '2125558493', 'NYC')
('Microscale Inc.', '2125551957', 'NYC')

**OBSERVACIÓN:** Se agregó la variable `city` para verificar

In [20]:
# Vemos las columnas de la tabla 'products'
pd.DataFrame.from_dict(inspector.get_columns('products'))

                 name         type default comment  nullable autoincrement
0         productCode  VARCHAR(15)    None    None     False           NaN
1         productName  VARCHAR(70)    None    None     False           NaN
2         productLine  VARCHAR(50)    None    None     False           NaN
3        productScale  VARCHAR(10)    None    None     False           NaN
4       productVendor  VARCHAR(50)    None    None     False           NaN
5  productDescription         TEXT    None    None     False           NaN
6     quantityInStock     SMALLINT    None    None     False         False
7            buyPrice       DOUBLE    None    None     False           NaN
8                MSRP       DOUBLE    None    None     False           NaN

In [21]:
# Hacemos una query para obtener el código y nombre de los productos del
# vendedor Gearbox Collectibles que tengan menos de 1000 unidades en stock.
mi_query = text("""
    SELECT productCode, productName, productVendor, quantityInStock
    FROM products
    WHERE productVendor = "Gearbox Collectibles"
    AND quantityInStock < 1000;
""")

query = conn.execute(mi_query)

# Se imprime el resultado:
for row in query:
    print(row)

('S18_2581', 'P-51-D Mustang', 'Gearbox Collectibles', 992)
('S18_2795', '1928 Mercedes-Benz SSK', 'Gearbox Collectibles', 548)

**OBSERVACIÓN:** Se agregaron las variables `productVendor` y `quantityInStock` para verificar

In [22]:
# Hacemos una query para obtener los tres productos más caros,
# desde el punto de visto de los comercializadores (`buyPrice`).
mi_query = text("""
    SELECT * FROM (
    SELECT productVendor, buyPrice,
    ROW_NUMBER() OVER(PARTITION BY productVendor ORDER BY buyPrice DESC) AS posicion
    FROM products
    ) n
    WHERE posicion <= 3
""")

query = conn.execute(mi_query)

# Se imprime el resultado:
for row in query:
    print(row)

('Autoart Studio Design', 95.34, 1)
('Autoart Studio Design', 61.34, 2)
('Autoart Studio Design', 60.86, 3)
('Carousel DieCast Legends', 82.34, 1)
('Carousel DieCast Legends', 67.56, 2)
('Carousel DieCast Legends', 60.78, 3)
('Classic Metal Creations', 98.58, 1)
('Classic Metal Creations', 98.3, 2)
('Classic Metal Creations', 69.93, 3)
('Exoto Designs', 72.82, 1)
('Exoto Designs', 69.78, 2)
('Exoto Designs', 66.92, 3)
('Gearbox Collectibles', 101.51, 1)
('Gearbox Collectibles', 73.49, 2)
('Gearbox Collectibles', 72.56, 3)
('Highway 66 Mini Classics', 83.51, 1)
('Highway 66 Mini Classics', 68.99, 2)
('Highway 66 Mini Classics', 68.29, 3)
('Min Lin Diecast', 93.89, 1)
('Min Lin Diecast', 91.92, 2)
('Min Lin Diecast', 51.61, 3)
('Motor City Art Classics', 85.68, 1)
('Motor City Art Classics', 84.76, 2)
('Motor City Art Classics', 68.8, 3)
('Red Start Diecast', 91.02, 1)
('Red Start Diecast', 77.27, 2)
('Red Start Diecast', 60.74, 3)
('Second Gear Diecast', 103.42, 1)
('Second Gear Diecast', 95.59, 2)
('Second Gear Diecast', 83.05, 3)
('Studio M Art Models', 58.33, 1)
('Studio M Art Models', 43.3, 2)
('Studio M Art Models', 34.21, 3)
('Unimax Art Galleries', 77.9, 1)
('Unimax Art Galleries', 74.86, 2)
('Unimax Art Galleries', 68.3, 3)
('Welly Diecast Productions', 89.14, 1)
('Welly Diecast Productions', 86.7, 2)
('Welly Diecast Productions', 77.9, 3)

In [23]:
# Hacemos una query para obtener a cantidad de productos por línea de producto (no las existencias en inventario)
mi_query = text("""
    SELECT productLine, COUNT(productCode)
    FROM products
    GROUP BY productLine;
""")

query = conn.execute(mi_query)

# Se imprime el resultado:
for row in query:
    print(row)

('Classic Cars', 38)
('Motorcycles', 13)
('Planes', 12)
('Ships', 9)
('Trains', 3)
('Trucks and Buses', 11)
('Vintage Cars', 24)

In [24]:
# Vemos las columnas de la tabla 'offices'
pd.DataFrame.from_dict(inspector.get_columns('offices'))

           name         type default comment  nullable
0    officeCode  VARCHAR(10)    None    None     False
1          city  VARCHAR(50)    None    None     False
2         phone  VARCHAR(50)    None    None     False
3  addressLine1  VARCHAR(50)    None    None     False
4  addressLine2  VARCHAR(50)    None    None      True
5         state  VARCHAR(50)    None    None      True
6       country  VARCHAR(50)    None    None     False
7    postalCode  VARCHAR(15)    None    None     False
8     territory  VARCHAR(10)    None    None     False

In [25]:
# Vemos las columnas de la tabla 'employees'
pd.DataFrame.from_dict(inspector.get_columns('employees'))

             name          type default comment  nullable autoincrement
0  employeeNumber       INTEGER    None    None     False         False
1        lastName   VARCHAR(50)    None    None     False           NaN
2       firstName   VARCHAR(50)    None    None     False           NaN
3       extension   VARCHAR(10)    None    None     False           NaN
4           email  VARCHAR(100)    None    None     False           NaN
5      officeCode   VARCHAR(10)    None    None     False           NaN
6       reportsTo       INTEGER    None    None      True         False
7        jobTitle   VARCHAR(50)    None    None     False           NaN

In [26]:
# La cantidad de empleados por país (tomando en cuenta la ubicación de la oficina).
mi_query = text("""
    SELECT offices.officeCode, offices.country, COUNT(employees.employeeNumber)
    FROM offices JOIN employees
    ON employees.officeCode = offices.officeCode
    GROUP BY offices.Country;
""")

query = conn.execute(mi_query)

# Se imprime el resultado:
for row in query:
    print(row)

('6', 'Australia', 4)
('4', 'France', 5)
('5', 'Japan', 2)
('7', 'UK', 2)
('1', 'USA', 10)

In [27]:
conn = db.connect()
inspector = inspect(db)

In [28]:
# Vemos las columnas de la tabla 'customers'
pd.DataFrame.from_dict(inspector.get_columns('customers'))

,name,type,default,comment,nullable,autoincrement
0,customerNumber,INTEGER,None,None,False,False
1,customerName,VARCHAR(50),None,None,False,NaN
2,contactLastName,VARCHAR(50),None,None,False,NaN
3,contactFirstName,VARCHAR(50),None,None,False,NaN
4,phone,VARCHAR(50),None,None,False,NaN
5,addressLine1,VARCHAR(50),None,None,False,NaN
6,addressLine2,VARCHAR(50),None,None,True,NaN
7,city,VARCHAR(50),None,None,False,NaN
8,state,VARCHAR(50),None,None,True,NaN
9,postalCode,VARCHAR(15),None,None,True,NaN
10,country,VARCHAR(50),None,None,False,NaN
11,salesRepEmployeeNumber,INTEGER,None,None,True,False
12,creditLimit,DOUBLE,None,None,True,NaN

In [29]:
# Vemos las columnas de la tabla 'payments'
pd.DataFrame.from_dict(inspector.get_columns('payments'))

             name         type default comment  nullable autoincrement
0  customerNumber      INTEGER    None    None     False         False
1     checkNumber  VARCHAR(50)    None    None     False           NaN
2     paymentDate         DATE    None    None     False           NaN
3          amount       DOUBLE    None    None     False           NaN

In [30]:
# El promedio de los pagos de cada uno de los clientes de España

mi_query = text("""
    SELECT customers.customerNumber, customers.customerName, AVG(payments.amount), customers.country
    FROM payments JOIN customers
    ON payments.customerNumber = customers.customerNumber
    WHERE customers.country = "Spain"
    GROUP BY payments.customerNumber;
""")

query = conn.execute(mi_query)

# Se imprime el resultado:
for row in query:
    print(row)

(141, 'Euro+ Shopping Channel', 55056.84461538462, 'Spain')
(216, 'Enaco Distributors', 22840.156666666666, 'Spain')
(344, 'CAF Imports', 23375.57, 'Spain')
(458, 'Corrida Auto Replicas, Ltd', 37480.03, 'Spain')
(484, 'Iberia Gift Imports, Corp.', 25493.925000000003, 'Spain')

**Observación:** Agregué `customers.country` para verificar que efectivamente se aplicó el filtro y la penúltima columna es efectivamente el promedio solicitado

# Manipulación de tablas con Pandas

In [31]:
conn = db.connect()
inspector = inspect(db)

Ahora se convertiran las tablas en Pandas dataframes y se harán las mismas "consultas" pero con puras funciones de Pandas

+ Esto es factible pues las tablas que hay en esta base de datos son relativamente pequeñas, entonces Python las puede manejar bien.

+ Pero si las tablas son de gran escala, lo recomendable es procesarla en un sistema de bases de datos hecho y derecho

In [32]:
# Como antes, se observa el nombre de las tablas en la base de datos
inspector.get_table_names()

['customers',
 'employees',
 'offices',
 'orderdetails',
 'orders',
 'payments',
 'productlines',
 'products']

+ Vamos a ocupar la función read_sql_table

In [33]:
conn = db.connect()
inspector = inspect(db)

In [34]:
# La tabla 'customers' se guarda como dataframe.
df_customers = pd.read_sql_table('customers', db)

# La tabla 'employees' se guarda como dataframe.
df_employees = pd.read_sql_table('employees', db)

# La tabla 'offices' se guarda como dataframe.
df_offices = pd.read_sql_table('offices', db)

# La tabla 'orderdetails' se guarda como dataframe.
df_orderdetails = pd.read_sql_table('orderdetails', db)

# La tabla 'orders' se guarda como dataframe.
df_orders = pd.read_sql_table('orders', db)

# La tabla 'payments' se guarda como dataframe.
df_payments = pd.read_sql_table('payments', db)

# La tabla 'productlines' se guarda como dataframe.
df_productlines = pd.read_sql_table('productlines', db)

# La tabla 'products' se guarda como dataframe.
df_products = pd.read_sql_table('products', db)

In [56]:
type(df_customers)

pandas.core.frame.DataFrame

In [57]:
# Se verificará que efectivamente es dataframe (sólo una)
# porque la instrucción es repetitiva
df_customers.head()

,customerNumber,customerName,contactLastName,contactFirstName,phone,addressLine1,addressLine2,city,state,postalCode,country,salesRepEmployeeNumber,creditLimit
0,103,Atelier graphique,Schmitt,Carine,40.32.2555,"54, rue Royale",None,Nantes,None,44000,France,1370.0,21000.0
1,112,Signal Gift Stores,King,Jean,7025551838,8489 Strong St.,None,Las Vegas,NV,83030,USA,1166.0,71800.0
2,114,"Australian Collectors, Co.",Ferguson,Peter,03 9520 4555,636 St Kilda Road,Level 3,Melbourne,Victoria,3004,Australia,1611.0,117300.0
3,119,La Rochelle Gifts,Labrune,Janine,40.67.8555,"67, rue des Cinquante Otages",None,Nantes,None,44000,France,1370.0,118200.0
4,121,Baane Mini Imports,Bergulfsen,Jonas,07-98 9555,Erling Skakkes gate 78,None,Stavern,None,4110,Norway,1504.0,81700.0

### La información de las líneas de productos

In [36]:
# Se verifica el tipo de datos de cada columna
df_productlines.dtypes

productLine        object
textDescription    object
htmlDescription    object
image              object
dtype: object

Se puede observar que todas la columnas son tipo string

In [58]:
# Se verifica el nombre de las columnas
df_productlines.columns

Index(['productLine', 'textDescription', 'htmlDescription', 'image'], dtype='object')

In [59]:
# Se obtiene el número de renglones y columnas
df_productlines.shape

(7, 4)

In [60]:
# Se obtiene el número de renglones y columnas
df_customers.shape

(122, 13)

Es decir que la tabla `productlines` tiene 7 renglones y 4 columnas

### Los empleados ordenados por nombre

In [39]:
# Se ordena por nombre (`firstName`) dicha tabla
# Pandas nos ayuda mucho pues ya tiene una función de sort_values... ordena alfabéticamente o numéricamente
df_employees.sort_values("firstName", ascending = True)

,employeeNumber,lastName,firstName,extension,email,officeCode,reportsTo,jobTitle
17,1611,Fixter,Andy,x101,afixter@classicmodelcars.com,6,1088.0,Sales Rep
5,1143,Bow,Anthony,x5428,abow@classicmodelcars.com,1,1056.0,Sales Manager (NA)
16,1504,Jones,Barry,x102,bjones@classicmodelcars.com,7,1102.0,Sales Rep
0,1002,Murphy,Diane,x5800,dmurphy@classicmodelcars.com,1,NaN,President
10,1286,Tseng,Foon Yue,x2248,ftseng@classicmodelcars.com,3,1143.0,Sales Rep
11,1323,Vanauf,George,x4102,gvanauf@classicmodelcars.com,3,1143.0,Sales Rep
13,1370,Hernandez,Gerard,x2028,ghernande@classicmodelcars.com,4,1102.0,Sales Rep
4,1102,Bondur,Gerard,x5408,gbondur@classicmodelcars.com,4,1056.0,Sale Manager (EMEA)
2,1076,Firrelli,Jeff,x9273,jfirrelli@classicmodelcars.com,1,1002.0,VP Marketing
8,1188,Firrelli,Julie,x2173,jfirrelli@classicmodelcars.com,2,1143.0,Sales Rep
15,1501,Bott,Larry,x2311,lbott@classicmodelcars.com,7,1102.0,Sales Rep
6,1165,Jennings,Leslie,x3291,ljennings@classicmodelcars.com,1,1143.0,Sales Rep
7,1166,Thompson,Leslie,x4065,lthompson@classicmodelcars.com,1,1143.0,Sales Rep
12,1337,Bondur,Loui,x6493,lbondur@classicmodelcars.com,4,1102.0,Sales Rep
20,1621,Nishi,Mami,x101,mnishi@classicmodelcars.com,5,1056.0,Sales Rep
22,1702,Gerard,Martin,x2312,mgerard@classicmodelcars.com,4,1102.0,Sales Rep
1,1056,Patterson,Mary,x4611,mpatterso@classicmodelcars.com,1,1002.0,VP Sales
14,1401,Castillo,Pamela,x2759,pcastillo@classicmodelcars.com,4,1102.0,Sales Rep
18,1612,Marsh,Peter,x102,pmarsh@classicmodelcars.com,6,1088.0,Sales Rep
9,1216,Patterson,Steve,x4334,spatterson@classicmodelcars.com,2,1143.0,Sales Rep
19,1619,King,Tom,x103,tking@classicmodelcars.com,6,1088.0,Sales Rep
3,1088,Patterson,William,x4871,wpatterson@classicmodelcars.com,6,1056.0,Sales Manager (APAC)
21,1625,Kato,Yoshimi,x102,ykato@classicmodelcars.com,5,1621.0,Sales Rep

### Los países donde hay oficinas.

In [40]:
# Simplemente seleccionamos la columna country y obtenemos sus valores únicos
df_offices['country'].unique()

array(['USA', 'France', 'Japan', 'Australia', 'UK'], dtype=object)

### El nombre y teléfono de los clientes de Nueva York (NYC)

In [61]:
# Condición de ser de NYC
condicion = (df_customers['city'] == 'NYC')

In [62]:
condicion

0      False
1      False
2      False
3      False
4      False
       ...
117    False
118    False
119    False
120    False
121    False
Name: city, Length: 122, dtype: bool

In [42]:
# El dataframe solicitado
df_customers[condicion][['customerName','phone']]

             customerName       phone
9       Land of Toys Inc.  2125557818
15     Muscle Machine Inc  2125557413
27        Vitachrome Inc.  2125551500
98   Classic Legends Inc.  2125558493
105       Microscale Inc.  2125551957

In [63]:
# Se imprime una verificación del filtro por ciudad
df_customers[condicion][['customerName','phone','city']]

             customerName       phone city
9       Land of Toys Inc.  2125557818  NYC
15     Muscle Machine Inc  2125557413  NYC
27        Vitachrome Inc.  2125551500  NYC
98   Classic Legends Inc.  2125558493  NYC
105       Microscale Inc.  2125551957  NYC

### El código y nombre de los productos del vendedor Gearbox Collectibles que tengan menos de 1000 unidades en stock.

In [44]:
condicion1 = (df_products['productVendor'] == 'Gearbox Collectibles')
condicion2 = (df_products['quantityInStock'] < 1000)

In [45]:
# El dataframe solicitado
df_products[condicion1 & condicion2][['productCode','productName']]

   productCode             productName
30    S18_2581          P-51-D Mustang
32    S18_2795  1928 Mercedes-Benz SSK

In [46]:
# Se imprime una verificación del filtro por vendedor
# y unidades en stock
columnas_requeridas = ['productCode','productName',
                       'productVendor','quantityInStock']
df_products[condicion1 & condicion2][columnas_requeridas]

   productCode             productName         productVendor  quantityInStock
30    S18_2581          P-51-D Mustang  Gearbox Collectibles              992
32    S18_2795  1928 Mercedes-Benz SSK  Gearbox Collectibles              548

### Los tres productos más caros, desde el punto de vista de los comercializadores

In [47]:
# Se obtiene el top3 por 'productVendor'
df_top3 = df_products.groupby(['productVendor'])['buyPrice'].nlargest(3)

# Se obtienen los índices de dichos precios
# Cuál es su nñumero de renglón en la tabla original
indices = df_top3.index.get_level_values(1)

# Se ocupan sólo los índices deseados
df_products_top3 = df_products.filter(items=indices, axis=0)

In [48]:
# La lista de productos solicitada
df_products_top3[['productVendor','productName','buyPrice']]

                 productVendor                           productName  buyPrice
6        Autoart Studio Design                     1968 Ford Mustang     95.34
64       Autoart Studio Design              1962 Volkswagen Microbus     61.34
57       Autoart Studio Design                     1997 BMW R 1100 S     60.86
62    Carousel DieCast Legends                 18th century schooner     82.34
41    Carousel DieCast Legends              Collectable Wooden Train     67.56
34    Carousel DieCast Legends           1913 Ford Model T Speedster     60.78
1      Classic Metal Creations              1952 Alpine Renault 1300     98.58
77     Classic Metal Creations               1956 Porsche 356A Coupe     98.30
53     Classic Metal Creations             1957 Corvette Convertible     69.93
69               Exoto Designs                     1952 Citroen-15CV     72.82
80               Exoto Designs     1992 Porsche Cayenne Turbo Silver     69.78
85               Exoto Designs                      1997 BMW F650 ST     66.92
25        Gearbox Collectibles        1998 Chrysler Plymouth Prowler    101.51
44        Gearbox Collectibles                 1976 Ford Gran Torino     73.49
32        Gearbox Collectibles                1928 Mercedes-Benz SSK     72.56
17    Highway 66 Mini Classics                       1993 Mazda RX-7     83.51
2     Highway 66 Mini Classics                 1996 Moto Guzzi 1100i     68.99
93    Highway 66 Mini Classics      Diamond T620 Semi-Skirted Tanker     68.29
24             Min Lin Diecast                      1995 Honda Civic     93.89
48             Min Lin Diecast                 1970 Triumph Spitfire     91.92
36             Min Lin Diecast                1999 Yamaha Speed Boat     51.61
4      Motor City Art Classics                   1972 Alfa Romeo GTA     85.68
51     Motor City Art Classics                      1940s Ford truck     84.76
100    Motor City Art Classics        America West Airlines B757-200     68.80
3            Red Start Diecast  2003 Harley-Davidson Eagle Drag Bike     91.02
21           Red Start Diecast           1980s Black Hawk Helicopter     77.27
37           Red Start Diecast   18th Century Vintage Horse Carriage     60.74
5          Second Gear Diecast                1962 LanciaA Delta 16V    103.42
7          Second Gear Diecast                     2001 Ferrari Enzo     95.59
12         Second Gear Diecast                      1969 Ford Falcon     83.05
16         Studio M Art Models                1940 Ford Pickup Truck     58.33
98         Studio M Art Models                         The Mayflower     43.30
54         Studio M Art Models                 1957 Ford Thunderbird     34.21
39        Unimax Art Galleries           1992 Ferrari 360 Spider red     77.90
27        Unimax Art Galleries                1964 Mercedes Tour Bus     74.86
38        Unimax Art Galleries                     1903 Ford Model A     68.30
10   Welly Diecast Productions                    1969 Corvair Monza     89.14
22   Welly Diecast Productions              1917 Grand Touring Sedan     86.70
8    Welly Diecast Productions                        1958 Setra Bus     77.90

### La cantidad de productos por línea de producto (no las existencias en inventario)

In [49]:
df_products['productLine'].value_counts()

productLine
Classic Cars        38
Vintage Cars        24
Motorcycles         13
Planes              12
Trucks and Buses    11
Ships                9
Trains               3
Name: count, dtype: int64

### La cantidad de empleados por país (tomando en cuenta la ubicación de la oficina)

In [50]:
# Se juntan las tablas de empleados y oficinas
# En Pandas los joins se hacen con con la función merge
df_empleado_oficina = pd.merge(df_employees, #tabla izquierda
                               df_offices, # tabla derecha
                               on='officeCode', how = 'inner')

# Recuerden que hay varios tipos de join: left, right, inner, outer,

df_empleado_oficina.head()

,employeeNumber,lastName,firstName,extension,email,officeCode,reportsTo,jobTitle,city,phone,addressLine1,addressLine2,state,country,postalCode,territory
0,1002,Murphy,Diane,x5800,dmurphy@classicmodelcars.com,1,NaN,President,San Francisco,+1 650 219 4782,100 Market Street,Suite 300,CA,USA,94080,NA
1,1056,Patterson,Mary,x4611,mpatterso@classicmodelcars.com,1,1002.0,VP Sales,San Francisco,+1 650 219 4782,100 Market Street,Suite 300,CA,USA,94080,NA
2,1076,Firrelli,Jeff,x9273,jfirrelli@classicmodelcars.com,1,1002.0,VP Marketing,San Francisco,+1 650 219 4782,100 Market Street,Suite 300,CA,USA,94080,NA
3,1088,Patterson,William,x4871,wpatterson@classicmodelcars.com,6,1056.0,Sales Manager (APAC),Sydney,+61 2 9264 2451,5-11 Wentworth Avenue,Floor #2,None,Australia,NSW 2010,APAC
4,1102,Bondur,Gerard,x5408,gbondur@classicmodelcars.com,4,1056.0,Sale Manager (EMEA),Paris,+33 14 723 4404,43 Rue Jouffroy D'abbans,None,None,France,75017,EMEA

+ Si el nombre de las columnas de la llave primaria es diferente en ambos dataframes, se ocupa la sintaxis

merged_df = pd.merge(df1, df2, left_on='name_column_df1', right_on='name_column_df2')

In [51]:
# Se hace el conteo solicitado
df_empleado_oficina['country'].value_counts()

country
USA          10
France        5
Australia     4
UK            2
Japan         2
Name: count, dtype: int64

### El promedio de los pagos de cada uno de los clientes de España.

In [52]:
# Se juntan las tablas de pagos y clientes
# Aquí tmb hacíamos un join
df_pagos_clientes = pd.merge(df_payments, df_customers,
                             on='customerNumber', how='inner')

df_pagos_clientes.head()

,customerNumber,checkNumber,paymentDate,amount,customerName,contactLastName,contactFirstName,phone,addressLine1,addressLine2,city,state,postalCode,country,salesRepEmployeeNumber,creditLimit
0,103,HQ336336,2004-10-19,6066.78,Atelier graphique,Schmitt,Carine,40.32.2555,"54, rue Royale",None,Nantes,None,44000,France,1370.0,21000.0
1,103,JM555205,2003-06-05,14571.44,Atelier graphique,Schmitt,Carine,40.32.2555,"54, rue Royale",None,Nantes,None,44000,France,1370.0,21000.0
2,103,OM314933,2004-12-18,1676.14,Atelier graphique,Schmitt,Carine,40.32.2555,"54, rue Royale",None,Nantes,None,44000,France,1370.0,21000.0
3,112,BO864823,2004-12-17,14191.12,Signal Gift Stores,King,Jean,7025551838,8489 Strong St.,None,Las Vegas,NV,83030,USA,1166.0,71800.0
4,112,HQ55022,2003-06-06,32641.98,Signal Gift Stores,King,Jean,7025551838,8489 Strong St.,None,Las Vegas,NV,83030,USA,1166.0,71800.0

In [53]:
# Se aplica el filtro del país
condicion_pais = (df_pagos_clientes['country'] == 'Spain')
df_pagos_clientes_espania = df_pagos_clientes[condicion_pais]
df_pagos_clientes_espania.head()

,customerNumber,checkNumber,paymentDate,amount,customerName,contactLastName,contactFirstName,phone,addressLine1,addressLine2,city,state,postalCode,country,salesRepEmployeeNumber,creditLimit
36,141,AU364101,2003-07-19,36251.03,Euro+ Shopping Channel,Freyre,Diego,(91) 555 94 44,"C/ Moralzarzal, 86",None,Madrid,None,28034,Spain,1370.0,227600.0
37,141,DB583216,2004-11-01,36140.38,Euro+ Shopping Channel,Freyre,Diego,(91) 555 94 44,"C/ Moralzarzal, 86",None,Madrid,None,28034,Spain,1370.0,227600.0
38,141,DL460618,2005-05-19,46895.48,Euro+ Shopping Channel,Freyre,Diego,(91) 555 94 44,"C/ Moralzarzal, 86",None,Madrid,None,28034,Spain,1370.0,227600.0
39,141,HJ32686,2004-01-30,59830.55,Euro+ Shopping Channel,Freyre,Diego,(91) 555 94 44,"C/ Moralzarzal, 86",None,Madrid,None,28034,Spain,1370.0,227600.0
40,141,ID10962,2004-12-31,116208.40,Euro+ Shopping Channel,Freyre,Diego,(91) 555 94 44,"C/ Moralzarzal, 86",None,Madrid,None,28034,Spain,1370.0,227600.0

In [54]:
# Se hace el cálculo de promedio solicitado
df_pagos_clientes_espania.groupby(['customerNumber'])['amount'].mean()

customerNumber
141    55056.844615
216    22840.156667
344    23375.570000
458    37480.030000
484    25493.925000
Name: amount, dtype: float64

In [55]:
#db.dispose()